services:
  linksforall-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=linksforall
      - POSTGRESQL_PASSWORD=linksforall
      - POSTGRESQL_DATABASE=linksforal-development
