name: 'LinksforAll::E2E Test'

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: linksforall_user
          POSTGRESQL_PASSWORD: linksforall_password
          POSTGRESQL_DATABASE: linksforall_db

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: "Intall dependencies"
        run: npm ci

      - name: Run prisma setup and test
        run: npx prisma migrate deploy && npx prisma generate && npm run test:e2e
        env:
          JWT_SECRET: a8f6dnpf6dfapdfyuadyf014117679tghavmvnfk
          DATABASE_URL: "postgresql://linksforall_user:linksforall_password@localhost:5432/linksforall_db?schema=public"

      - name: 'Report Coverage'
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
